/**
 * Shared config for e2e tests — reads ports and settings from config.json
 * (generated by `bb bin/export-config json` / `make config.json`).
 */

import { existsSync, readFileSync } from "fs";
import { join } from "path";

const configPath = join(__dirname, "..", "config.json");
if (!existsSync(configPath)) {
  throw new Error(
    `config.json not found — run 'make config.json' first`
  );
}

const raw = JSON.parse(readFileSync(configPath, "utf-8"));

export const API_PORT: number = raw.server.port;
export const DASHBOARD_PORT: number = raw.server["dashboard-port"];
export const BASE_URL = `http://localhost:${API_PORT}`;
export const DASHBOARD_URL = `http://localhost:${DASHBOARD_PORT}`;
